version: '3'
services:
  mongodb:
    build: 
      dockerfile: ./Dockerfile
      context: .
    image: diegoparente/mongodb
    container_name: mongodb
    networks:
      - docker-web
    ports:
      - "27017"

networks:
  docker-web:
    driver: bridge
